### ISSUE TITLE
Expected result not visible

### ISSUE THREAD

**Issue by nchapman** [mozilla/universal-search-content#116] opened 2015-12-04 22:58 UTC
I am trying to navigate to the universal search content repo, but it doesn't show up when I type universal search:

![screen shot 2015-12-04 at 2 49 37 pm](https://cloud.githubusercontent.com/assets/3095/11603496/ef89541a-9a96-11e5-85f3-4f4d8dcc07fb.png)

Here's 42.0 without the add-on

![screen shot 2015-12-04 at 2 53 45 pm](https://cloud.githubusercontent.com/assets/3095/11603500/f3c147fe-9a96-11e5-9cc7-a11c4a95e4ff.png)

Here's 44.0 dev edition

![screen shot 2015-12-04 at 2 52 37 pm](https://cloud.githubusercontent.com/assets/3095/11603499/f19a6e60-9a96-11e5-8e55-dec40f4e5f9d.png)

This could be a situation where we need to show fewer search suggestions. It is strange though that the content repo is the top result in the other two examples.

**Comment by chuckharmston** [comment] 2015-12-06 20:41
I'll defer to @6a68 on possible reasons for this, as he has a better understanding of how these are queried.

I do think that https://github.com/mozilla/universal-search-addon/issues/159 will help us work through this UX. It may be that we want to separate blocks of Places results by type, to make sure that any open tabs or bookmarks are surfaced, plus some additional number of search suggestions.
- Up to 2 open tabs, ordered by frecency.
- Up to 2 bookmarks, ordered by frecency.
- 6 history items, minus 1 for each open tab or bookmark shown, ordered by frecency.
- Up to 2 search suggestions.

**Comment by jaredhirsch** [comment] 2015-12-10 05:20
I think we are going to need to see the packets passed to the iframe, if we're going to have any shot at debugging these kinds of subtle quality issues.

I'll permanently enable the console logging of those packets (https://github.com/mozilla/universal-search-addon/issues/162), and we can just start pastebinning that data when submitting search quality bugs like this one. To get the word out about this requirement, I'll email the firefox-search list, and include this requirement in our CONTRIBUTING.md doc.

I'm conveniently unable to reproduce your issue ;-)

<img width="723" alt="screenshot 2015-12-09 23 30 35" src="https://cloud.githubusercontent.com/assets/96396/11707027/e1c6d278-9ecc-11e5-930f-751a1983bf9e.png">

Our places search is a simplified version of what's in desktop FF today (roughly 5-10x less code). Without getting into the weeds too much, we're doing 1 search instead of 5-9 slightly different parallel searches; we're only matching on boundaries in one way, where the production code will start with a less fuzzy match, then use a more liberal match if few results are returned; and we simplify some of the other search parameters.

While we could reduce divergence today, by copy-pasting the entire existing service, I actually think our search will perform better really soon, as we add new engagement metrics, full-text search, etc.

So, at risk of being a bit frustrating, I'm going to close this--but please, reopen if you can get the packets.

We need to figure out a normalized quality metric that can be used for search suggestions and places results; until we do, we could roll with the "frecency > 1000" metric used by the current code (I've filed https://github.com/mozilla/universal-search-content/issues/134 for this). Alternatively, we could use the more precisely segmented approach Chuck mentioned in his comment. Let's discuss that further in #134.

Closing. :beers:

**Closed as completed by jaredhirsch** 2015-12-10 05:20 UTC
