### ISSUE TITLE
Odd workflow when you're offline

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search-content#93] opened 2015-11-30 19:21 UTC
The Internet fell over this morning (in MTV and elsewhere). I was trying to browse to a site to see if the Internet was back, and was greeted with this user experience:

![new_tab_and_irccloud_and_1__pdehaan_pdehaan____dev_tmp_ini_test__zsh_](https://cloud.githubusercontent.com/assets/557895/11481478/8c839b1a-9752-11e5-8593-1bbb2bffaa4c.png)
**FIGURE 1:** https://d1fnkpeapwua2i.cloudfront.net/ was down and unreachable due to poor wifi connectivity.

I couldn't even type a URL and pressing Enter, since it seems like Enter is captured or ignored or piped to cloudfront.net (which wasn't reachable).
I _WAS_ able to type in a URL and then press the little :arrow_right: button in the address bar.

Not sure if there is an easy way to see if there is an internet connection and either disable the add-on, or provide a somewhat better experience.

**Comment by chuckharmston** [comment] 2015-12-01 03:31
Yeah, this is known, and we have some ideas for addressing. Closing as a dupe of https://github.com/mozilla/universal-search-addon/issues/98

**Closed as completed by chuckharmston** 2015-12-01 03:31 UTC
Labels: duplicate
